# Generated by Django 6.0 on 2025-12-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='moeda',
            field=models.CharField(choices=[('BRL', 'Real (R$)'), ('USD', 'Dólar (US$)')], default='BRL', max_length=3),
        ),
    ]
