# Generated by Django 6.0 on 2025-12-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_investimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='ultimo_deposito',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
